from math import ceil
altura = float(input("Digite a altura do cilindro a ser pintado: "))
raio = float(input("Digite o raio o raio do cilindro a ser pintado: "))
areaCilindro= (3.1415*raio*raio) + (altura*2*3.1415*raio)
litros = areaCilindro/3
latas = ceil(litros/5)
print(latas)
if latas == 1:
    print(f"Altura: {altura}")
    print(f"Raio: {raio}")
    print(f"Área a ser pintada: {areaCilindro:.2f}")
    print(f"Qtde de litros necessários: {litros:.2f}")
    print(f"Qtde de latas de tinta: {latas}")
    print(f"Preço unitário da lata: R$ 50.00")
    print(f"Custo total: R$ {latas*50}.00")
elif latas == 2:
    print(f"Altura: {altura}")
    print(f"Raio: {raio}")
    print(f"Área a ser pintada: {areaCilindro:.2f}")
    print(f"Qtde de litros necessários: {litros:.2f}")
    print(f"Qtde de latas de tinta: {latas}")
    print(f"Preço unitário da lata: R$ 48.00")
    print(f"Custo total: R$ {latas*48}.00")
elif latas == 3:
    print(f"Altura: {altura}")
    print(f"Raio: {raio}")
    print(f"Área a ser pintada: {areaCilindro:.2f}")
    print(f"Qtde de litros necessários: {litros:.2f}")
    print(f"Qtde de latas de tinta: {latas}")
    print(f"Preço unitário da lata: R$ 46.00")
    print(f"Custo total: R$ {latas*46}.00")
elif latas > 3:
    print(f"Altura: {altura}")
    print(f"Raio: {raio}")
    print(f"Área a ser pintada: {areaCilindro:.2f}")
    print(f"Qtde de litros necessários: {litros:.2f}")
    print(f"Qtde de latas de tinta: {latas}")
    print(f"Preço unitário da lata: R$ 45.00")
    print(f"Custo total: R$ {latas*45}.00")